pipeline {
    agent {
        docker {
            image 'node:19-bullseye' 
            args '-p 3000:3000' 
        }
    }
    stages {
        stage('Test Docker') {
            steps {
                script {
                    sh 'docker info'
                    sh 'docker network ls'
                }
            }
        }
        stage('Build') { 
            steps {
                dir('frontend') {
                    sh 'npm install'
                }
            }
        }        
        stage('Test') { 
            steps {
                dir('frontend') {
                    sh 'npm test'
                }
            }
        }
        stage('Complete') {
            steps {
                echo 'Job Complite!'
           }
        }
    }
}