version: "3.8"
services: 
  mongodb:
    image: "mongo" 
  backend:
    build: ./backend
    ports:
      - '80:80'
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    